### ISSUE TITLE
request for small change

### ISSUE THREAD

**Issue by hynek2001** [ip6li/ejbca-setup#16]
hi. first of all. great job. thank you ! you saved me alots of hours ;)

and now, my request:
could you change "  to ' for database password ?

i mean to change row :
database_password="very***bad***database***password"
to :
database_password='very***bad***database***password'

reason is, when i used $$ on end on my password, it was interpreted as number, and script fail to access database...

**Comment by ip6li** [comment]
fixed: 74534ce945e6caabc2fa396a03950abb0e523c88
