### ISSUE TITLE
java dependency not met

### ISSUE THREAD

**Issue by paul-at-k** [ip6li/ejbca-setup#17]
It downloads wildfire and unpacks it. It then installs with lots of errors similar to:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by __redirected.__SAXParserFactory (file:/var/lib/ejbca/wildfly-10.1.0.Final/jboss-modules.jar) to constructor com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl()
WARNING: Please consider reporting this to the maintainers of __redirected.__SAXParserFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
From my reading these seem to be benign. Then it starts installing ejbca itself before the following error:
```
jar:
    [mkdir] Created dir: /var/lib/ejbca/ejbca_ce_6_10_1_2/modules/cesecore-p11/build
    [javac] Compiling 1 source file to /var/lib/ejbca/ejbca_ce_6_10_1_2/modules/cesecore-p11/build
    [javac] /var/lib/ejbca/ejbca_ce_6_10_1_2/modules/cesecore-p11/src/sun/security/pkcs11/CESeCoreUtils.java:15: error: package sun.security.pkcs11.wrapper is not visible
    [javac] import static sun.security.pkcs11.wrapper.PKCS11Constants.CKA_SENSITIVE;

```
Lots of missing symbols then a statement that the build has failed. It then hangs deploying EJBCA.

**Comment by ip6li** [comment]
Which platform/operating system/version?
Which EJBCA version?
Please do not use version enclosed in EJBCA. Clone master from this repository.

**Comment by paul-at-k** [comment]
Thanks IP6li. Looks like there was an ommission in the doc that I was following:
https://www.ejbca.org/docs/Quick_Start_Guide.html

Even though I had JDK8 installed it wasn't set as the default. Needed to do the following also:

sudo update-java-alternatives --set java-1.8.0-openjdk-amd64
