### ISSUE TITLE
Remove downloaded files if checksum verification fails

### ISSUE THREAD

**Issue by primetomas** [ip6li/ejbca-setup#2]
If checksum verification fails the files are kept. So if running the script a second time (after removing ejbca-custom) the corrupted (potentially malicious) files will be used.

I simply added a "rm".

    if [ $? -ne 0 ]; then
       echo "SHA256 for mariadb-java-client does not match"
       exit 1
    fi
    rm mariadb-java-client-${MARIADB_CONNECTOR_VERSION}.jar
    cd ..

<snip>

    if [ $? -ne 0 ]; then
       echo "SHA256 for EJBCA does not match"
       exit 1
    fi
    rm ejbca_ce_${EJBCA_VERSION}.zip
    cd ..

**Comment by ip6li** [comment]
9a3eff9f8d41f9b2eb89e0e890183e52f5ad23f8
