### ISSUE TITLE
Use 2048 bit keys for client and server keys

### ISSUE THREAD

**Issue by primetomas** [ip6li/ejbca-setup#3]
It seems overly slow to use 4096 bit keys for the TLS server and superadmin client keystores. 2048 bit keys are the current common RSA key lengths for this, with 4096 being used on Root CAs, and sometimes Issuing CAs.

batchtool.properties only defines these client+TLS server generated keys and can be lowered to 2048.

    @@ -407,7 +426,7 @@ keys.alg=RSA
    # Examples: 1024 for RSA or DSA and prime256v1 for ECDSA
    #
    # Default: 2048
    -keys.spec=4096
    +keys.spec=2048

**Comment by ip6li** [comment]
9a3eff9f8d41f9b2eb89e0e890183e52f5ad23f8
