### ISSUE TITLE
Use default context root for certificate and CRL store

### ISSUE THREAD

**Issue by primetomas** [ip6li/ejbca-setup#4]
Could we use the default context root for these?

    @@ -420,7 +439,7 @@ certstore.enabled=true 
    # Context root (the path in the URL)
    # Default is '/certificates'
    -certstore.contextroot=/ejbca/publicweb/certificates
    +#certstore.contextroot=/ejbca/publicweb/certificates

    @@ -688,7 +706,7 @@ crlstore.enabled=true
    # Context root (the path in the URL)
    # Default is '/crls'
    -crlstore.contextroot=/ejbca/publicweb/crls
    +#crlstore.contextroot=/ejbca/publicweb/crls

**Comment by ip6li** [comment]
9a3eff9f8d41f9b2eb89e0e890183e52f5ad23f8
