### ISSUE TITLE
Remove included properties files that are not used

### ISSUE THREAD

**Issue by primetomas** [ip6li/ejbca-setup#5]
The install script creates properties files where some are not used. It would trim down the script, and possibly make it easier for a user to sift through the needed options if we limited the properties files to those needed. Some of them should not be used for most installations. I suggest to remove the following properties files from the script which are not used, and shouldn't be changed at all in most installations:
- log.properties
- mail.properties
- ocsp.properties
- scepra.properties
- va.properties

**Comment by primetomas** [comment]
These two parameters in the beginning can also then be removed.

    scep_ra_keyStorePassword_1="geheim"
    scep_ra_datasource_password="ejbca"

**Comment by ip6li** [comment]
1461019dae35d78bb4666e9450d054e97e199c18
